name: Publish PDFs
on:
  push:
    branches: [main]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            cv-en.tex
            cv-es.tex
            cv-pt.tex
      - name: Grab PDFs
        run: mkdir -p pdf && mv ./cv-en.pdf ./cv-es.pdf ./cv-pt.pdf ./pdf/
      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./pdf
          publish_branch: pdf
          force_orphan: true
          enable_jekyll: true
